service: test-angular-universal

frameworkVersion: ">=1.14.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  stage: v1

package:
  include:
    - lambda.js
    - node_modules/core-js/client/shim.min.js
    - node_modules/zone.js/dist/zone.min.js
    - src/favicon.ico
    - src/index-lambda.html
    - src/styles.css
    - src/dist/build.js
    - src/dist/lambda.js
  exclude:
    - node_modules/**
    - src/**
    - e2e/**
    - package.json
    - yarn.lock
    - coverage/**
    - .**
    - karma.conf.js
    - protractor.conf.js
    - LICENSE
    - README.md
    - bs-config.aot.js
    - tslint.json
    - tsconfig**.json
    - webpack.**.js

functions:
  handler:
    handler: lambda.handler
    timeout: 120
    memorySize: 128
    events:
      - http:
          path: '{proxy+}'
          method: get

