service: test-angular-universal

frameworkVersion: ">=1.14.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  stage: dev

package:
  include:
    - dist_lambda/lambda.js
    - dist/**
  exclude:
    - node_modules/**
    - src/**
    - e2e/**
    - package.json
    - yarn.lock
    - coverage/**
    - .**
    - karma.conf.js
    - protractor.conf.js
    - LICENSE
    - README.md
    - dist**/**
    - bs-config**.js
    - tslint.json
    - tsconfig**.json
    - webpack.**.js

functions:
  handler:
    handler: dist_lambda/lambda.handler
    timeout: 120
    memorySize: 128
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

